const actionsTypesOneQuestion={
    LOADING_SUCCESS_QUESTION:"LOADING_SUCCESS_QUESTION",
    LOAD_SUCCESS_QUESTION:"LOAD_SUCCESS_QUESTION",
    LOAD_FAILURE_QUESTION:"LOAD_FAILURE_QUESTION"
}

export default actionsTypesOneQuestion